### ISSUE TITLE
Подключить к Mysql

### ISSUE THREAD

**Issue by loveorigami** [yurii-github/yii2-mylib#4]
Здравствуйте.
Появилась необходимость подключить БД к Mysql.

переписал console-config
```
if (file_exists($mylib_config_file)) {
  $mylib_config = json_decode(file_get_contents($mylib_config_file));
  $console_config['components']['db']['dsn'] = 'mysql:host=127.0.0.1;port=3306;dbname=ori_lib';
  $console_config['components']['db']['username'] = 'root';
}

return $console_config;
```

Вроде бы все получилось, таблицы появились, синхронизация происходит есть и записи, есть и обложки в бд. Но в гриде они не выводятся.

 в консоли пишется ошибка - Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by loveorigami** [comment]
Подробнее ошибка в следующем
```
Exception 'Error' with message 'Call to undefined method PDO::sqliteCreateFunction()' 

in X:\domains\ori.lib\app\controllers\api\BookController.php:61

Stack trace:
#0 [internal function]: app\controllers\api\BookController->actionIndex()
#1 X:\domains\ori.lib\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#2 X:\domains\ori.lib\vendor\yiisoft\yii2\base\Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#3 X:\domains\ori.lib\vendor\yiisoft\yii2\base\Module.php(523): yii\base\Controller->runAction('', Array)
#4 X:\domains\ori.lib\vendor\yiisoft\yii2\web\Application.php(102): yii\base\Module->runAction('api/book', Array)
#5 X:\domains\ori.lib\vendor\yiisoft\yii2\base\Application.php(380): yii\web\Application->handleRequest(Object(yii\web\Request))
#6 X:\domains\ori.lib\app\public\index.php(24): yii\base\Application->run()
#7 {main}
```

**Comment by yurii-github** [comment]
это еще актуально?

**Comment by yurii-github** [comment]
починил
